config/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('library.urls' , 'library') , namespace= 'library')),
]

library/urls.py
from django.urls import path
from .views import Book_list , search , index , member_create

urlpatterns = [
    path('', index , name= 'index'),
    path('books/', Book_list.as_view() , name= 'book_list'),
    path('member_create/' , member_create , name= 'member_create'),
    path('search/', search , name= 'search'),
]

library/models.py
from django.db import models

class Member(models.Model):
    name = models.CharField(max_length= 100)
    family = models.CharField(max_length= 100)
    phone_number = models.IntegerField()
    address = models.CharField(max_length= 500)

    def __str__(self):
        return self.name + ' ' + self.family

class Librarian(models.Model):
    name = models.CharField(max_length= 100)
    family = models.CharField(max_length= 100)
    phone_number = models.IntegerField()
    address = models.CharField(max_length= 500)

    def __str__(self):
        return self.name + ' ' + self.family



class Author(models.Model):
    full_name = models.CharField(max_length= 200)
    country = models.CharField(max_length= 200)

    def __str__(self):
        return self.full_name

class Subject(models.Model):
    subject = models.CharField(max_length= 200)
    
    def __str__(self):
        return self.subject

class Category(models.Model):
    category = models.CharField(max_length= 200)

    def __str__(self):
        return self.category


class Book(models.Model):
    name = models.CharField(max_length= 200)
    author = models.ForeignKey(Author, on_delete= models.CASCADE,)
    subject = models.ForeignKey(Subject, on_delete= models.CASCADE,)
    category = models.ForeignKey(Category, on_delete= models.CASCADE,)
    published_date = models.DateField()

    def __str__(self):
        return self.name


class Reserved_Book(models.Model):
    memmber = models.ForeignKey(Member, on_delete= models.CASCADE,)
    book = models.ForeignKey(Book, on_delete= models.CASCADE,)
    reserve_date_start = models.DateField()
    reserve_date_end = models.DateField()

    
    def __str__(self):
        return self.memmber.name + " " + self.memmber.family

library/forms.py
from django import forms 

from .models import Member

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = '__all__'

library/views.py
from django.shortcuts import render , redirect
from django.views import View
from django.contrib import messages
from django.db.models import Q

from .models import Book
from .forms import MemberForm

def index(request):
    return render (request, 'library/index.html')


class Book_list(View):
    
    def get (self , request):
        book = Book.objects.all()
        return render (request, 'library/book_list.html', {'book':book})


def member_create(request):
    form = MemberForm(request.POST)
    if form.is_valid():
        name = form.cleaned_data['name'] 
        family = form.cleaned_data ['family'] 
        phone_number = form.cleaned_data ['phone_number'] 
        address = form.cleaned_data ['address'] 
        form.save()
        messages.add_message(request, messages.SUCCESS, ' با موفقیت ثبت شد')
        return redirect('/member_create/')
    else:
        form = MemberForm
        return render(request,'library/member_create.html', {'form':form})




def search (request, **kwargs):
    if request.method == 'GET':
        query = request.GET.get('search')
    book_result = Book.objects.filter(
        Q(name__icontains=query) | Q(author__full_name=query) | Q(subject__subject=query) 
    ) 
        
  
    return render (request, 'library/book_search.html' , {'book_result':book_result, 'query':query})

library/templates/library/book_list.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>کتاب ها</title>
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'library:index' %}">خانه</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'library:book_list' %}">کتاب ها</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'library:member_create' %}">ثبت نام</a>
              </li>
              
            </ul>
            <form class="d-flex" action="{% url 'library:search' %}">
              <input class="form-control me-2" type="search" name="search" placeholder="کتاب، نویسنده، موضوع " aria-label="Search">
              <button class="btn btn-outline-success" type="submit">جستجو</button>
            </form>
          </div>
        </div>
    </nav>

    <br><br>
    <h1 style="text-align: center;">لیست کل کتاب ها</h1>
    {% for b in book %}
        <div class="card">
            <div class="card-header">
    
            </div>

            <div class="card-body">
                <h5 class="card-title">{{b.name}}</h5>
                <p class="card-text">{{b.author}}</p>
                <p class="card-text">{{b.subject}}</p>
          </div>
        </div>
        {% endfor %}
    
</body>
</html>

library/templates/library/book_search.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>جستجو</title>
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'library:index' %}">خانه</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'library:book_list' %}">کتاب ها</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'library:member_create' %}">ثبت نام</a>
              </li>
              
            </ul>
            <form class="d-flex" action="{% url 'library:search' %}">
              <input class="form-control me-2" type="search" name="search" placeholder="کتاب، نویسنده، موضوع " aria-label="Search">
              <button class="btn btn-outline-success" type="submit">جستجو</button>
            </form>
          </div>
        </div>
    </nav>
    
    <h1 style="text-align: center;">'جستجو بر اساس  '{{query}}</h1>
    {% for b in book_result %}
    <div class="card">
        <div class="card-header">
    
        </div>

        <div class="card-body">
            <h5 class="card-title">{{b.name}}</h5>
            <p class="card-text">{{b.author}}</p>
            <p class="card-text">{{b.subject}}</p>
        </div>
    </div>
    {% endfor %}
    
</body>
</html>

library/templates/library/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>خانه</title>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'library:index' %}">خانه</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'library:book_list' %}">کتاب ها</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'library:member_create' %}">ثبت نام</a>
              </li>
              
            </ul>
            <form class="d-flex" action="{% url 'library:search' %}">
              <input class="form-control me-2" type="search" name="search" placeholder="کتاب، نویسنده، موضوع " aria-label="Search">
              <button class="btn btn-outline-success" type="submit">جستجو</button>
            </form>
          </div>
        </div>
      </nav>
</body>
</html>

library/templates/library/member_create.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>ثبت نام</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'library:index' %}">خانه</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'library:book_list' %}">کتاب ها</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'library:member_create' %}">ثبت نام</a>
              </li>
              
            </ul>
            <form class="d-flex" action="{% url 'library:search' %}">
              <input class="form-control me-2" type="search" name="search" placeholder="کتاب، نویسنده، موضوع " aria-label="Search">
              <button class="btn btn-outline-success" type="submit">جستجو</button>
            </form>
          </div>
        </div>
      </nav>

    <form class="row g-3" method="POST">
        {% csrf_token %}  
        
        <div class="col-md-6">
          <label for="name" class="form-label">نام</label> 
          <input type="text" class="form-control" id="name" name="name">
        </div>
        <div class="col-md-6">
          <label for="family" class="form-label">نام خانوادگی</label>
          <input type="text" class="form-control" id="family" name="family">
        </div>
        <div class="col-md-6">
            <label for="phone_number" class="form-label">شماره ی موبایل</label>
            <input type="number" class="form-control" id="phone_number" name="phone_number">
        </div>
        <div class="col-md-6">
            <label for="address" class="form-label"> آدرس </label>
            <input type="text" class="form-control" id="address" name="address">
        </div>
        <div class="col-12">
          <button type="submit" class="btn btn-success">ثبت</button>
          </div>
    </form> 
    
    {% if messages %}
        {% for msg in messages %}
            <div class="alert alert-success" role="alert">
                <p> {{msg}}</p>
            </div>
        {% endfor %}
    {% endif %}
</body>
</html>